[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
# better deterministic deploys
bytecode_hash = "none"
remappings = [
    "forge-std/=dependencies/forge-std-1.9.7/src/",
    "create2-helpers/=dependencies/create2-helpers-0.5.0/src/",
    "deterministic-proxy-factory/=dependencies/deterministic-proxy-factory-0.1.4/src/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.3.0/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.3.0/",
    "tempo-std/=dependencies/tempo-std-0.1.1/src/",
]
optimizer_runs = 200
via_ir = true
solc_version = "0.8.30"
fs_permissions = [
    { access = "read", path = "out" },
    { access = "read", path = "forge-utils" },
]

[profile.ci]

[profile.gambit]
optimizer = false
via_ir = false
dynamic_test_linking = false

[bind_json]
out = "forge-utils/JsonBindings.sol"

[fmt]
line_length = 100
single_line_statement_blocks = "multi"
sort_imports = true
contract_new_lines = true
bracket_spacing = true
number_underscore = "thousands"
wrap_comments = true

[lint]
exclude_lints = [
    "erc20-unchecked-transfer",
    "mixed-case-function",
    "mixed-case-variable",
    "unwrapped-modifier-logic",
]


[dependencies]
forge-std = "1.9.7"
create2-helpers = "0.5.0"
deterministic-proxy-factory = "0.1.4"
"@openzeppelin-contracts-upgradeable" = "5.3.0"
"@openzeppelin-contracts" = "5.3.0"
tempo-std = { version = "0.1.1", git = "https://github.com/tempoxyz/tempo-std.git" }
auth-registry = { version = "1", git = "git@github.com:withbridge/auth-registry.git", rev = "b2d140f8fc4675cd35c9671d1e090fecb0cc5928" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
